### ISSUE TITLE
Unable to configure on Windows.

### ISSUE THREAD

**Issue by sduensin** [remeh/mehstation#2]
I unpacked the Windows zip, read the wiki, and was unable to find a database file to edit.

**Comment by remeh** [comment]
Hey!
It is indeed a bug if `mehstation-config` doesn't directly opens the good directory containing the `mehstation.db`

I'll look more accurately in this bug in the following days but ATM on Windows you should find a subdirectory mehstation in `"C:/Users/<USER>/AppData/Local/"` or `"C:/ProgramData/"` containing the `mehstation.conf` and `mehstation.db` file. If I'm wrong, the Windows build have a serious bug that I have to investigate.

I'll fix this quickly but I hope this quick fix will do it for you, thanks for the feedback!

**Comment by remeh** [comment]
I think I've found the problem: it is necessary to run `mehstation` first to init the original files and then `mehstation-config` will automatically open the good directory containing the database.db file. I have to document it somewhere.
