### ISSUE TITLE
Special Characters not rendered properly

### ISSUE THREAD

**Issue by HerbFargus** [remeh/mehstation#4]
The trademark
![trademark](https://cloud.githubusercontent.com/assets/10035308/13731345/038eb8a4-e92c-11e5-9ffe-7c9fc9d49962.png)
and the umlaut `ö` among others 
![umlaught](https://cloud.githubusercontent.com/assets/10035308/13731346/0391f762-e92c-11e5-8fcb-dd454bc290a2.png)

**Comment by remeh** [comment]
Nice catch, thanks !

**Comment by remeh** [comment]
Fixed by 45ea34388f5c6729d9aba1babf65a15b9eb7a30a

**Comment by HerbFargus** [comment]
Brilliant! Thanks mate
